/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ITimelockDelaySource,
  ITimelockDelaySourceInterface,
} from "../../../../artifacts/contracts/AethelredBridge.sol/ITimelockDelaySource";

const _abi = [
  {
    inputs: [],
    name: "getMinDelay",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class ITimelockDelaySource__factory {
  static readonly abi = _abi;
  static createInterface(): ITimelockDelaySourceInterface {
    return new Interface(_abi) as ITimelockDelaySourceInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ITimelockDelaySource {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as ITimelockDelaySource;
  }
}
