/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../../common";
import type {
  MockTokenMessengerV2,
  MockTokenMessengerV2Interface,
} from "../../../../artifacts/contracts/mocks/MockTokenMessengerV2";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "target",
        type: "address",
      },
    ],
    name: "AddressEmptyCode",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
    ],
    name: "AddressInsufficientBalance",
    type: "error",
  },
  {
    inputs: [],
    name: "FailedInnerCall",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "token",
        type: "address",
      },
    ],
    name: "SafeERC20FailedOperation",
    type: "error",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint64",
        name: "nonce",
        type: "uint64",
      },
      {
        indexed: true,
        internalType: "address",
        name: "token",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint32",
        name: "destinationDomain",
        type: "uint32",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "mintRecipient",
        type: "bytes32",
      },
    ],
    name: "BurnDeposited",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        internalType: "uint32",
        name: "destinationDomain",
        type: "uint32",
      },
      {
        internalType: "bytes32",
        name: "mintRecipient",
        type: "bytes32",
      },
      {
        internalType: "address",
        name: "burnToken",
        type: "address",
      },
    ],
    name: "depositForBurn",
    outputs: [
      {
        internalType: "uint64",
        name: "",
        type: "uint64",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "nonce",
    outputs: [
      {
        internalType: "uint64",
        name: "",
        type: "uint64",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x60808060405234610016576102dc908161001c8239f35b600080fdfe608060408181526004918236101561001657600080fd5b600092833560e01c9182636fd3504e1461006457505063affed0e01461003b57600080fd5b3461006057816003193601126100605767ffffffffffffffff60209254169051908152f35b5080fd5b8385913461023f57608036600319011261023f578335602490813563ffffffff811680910361023b576064356001600160a01b0381169490859003610237576020978882016323b872dd60e01b815233868401523060448401528460648401526064835260a083019267ffffffffffffffff9381811085821117610225578952518991829190828a5af13d15610219573d9083821161020757885191601f19603f81601f84011601168301838110868211176101f5578a52825261013091903d8b8d84013e5b88610243565b80518a81151591826101d0575b505090506101ba57875494600183871601918383116101a9575050917f6d0af48c94e70b89be20a31e386da5fcc22b21c13c8b33c80eda6bd5e77fae9c9391606093169788809667ffffffffffffffff191617905586519182528882015260443586820152a351908152f35b634e487b7160e01b8a526011905288fd5b8651635274afe760e01b81529081018690528490fd5b83809293500103126101f1578901518015908115036101f157808a8c61013d565b8880fd5b634e487b7160e01b8c5260418552888cfd5b634e487b7160e01b8a5260418352868afd5b6101309060609061012a565b634e487b7160e01b8b5260418452878bfd5b8680fd5b8580fd5b8280fd5b9061026a575080511561025857805190602001fd5b604051630a12f52160e11b8152600490fd5b8151158061029d575b61027b575090565b604051639996b31560e01b81526001600160a01b039091166004820152602490fd5b50803b1561027356fea2646970667358221220fa3755b2472f909359ecdd0fa0b45390ecb9d9dc358f71bea9191d7114b1219264736f6c63430008140033";

type MockTokenMessengerV2ConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: MockTokenMessengerV2ConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class MockTokenMessengerV2__factory extends ContractFactory {
  constructor(...args: MockTokenMessengerV2ConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      MockTokenMessengerV2 & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(
    runner: ContractRunner | null
  ): MockTokenMessengerV2__factory {
    return super.connect(runner) as MockTokenMessengerV2__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): MockTokenMessengerV2Interface {
    return new Interface(_abi) as MockTokenMessengerV2Interface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): MockTokenMessengerV2 {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as MockTokenMessengerV2;
  }
}
