/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type {
  Signer,
  BigNumberish,
  ContractDeployTransaction,
  ContractRunner,
} from "ethers";
import type { NonPayableOverrides } from "../../../../common";
import type {
  MockAggregatorV3,
  MockAggregatorV3Interface,
} from "../../../../artifacts/contracts/mocks/MockAggregatorV3";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint8",
        name: "feedDecimals",
        type: "uint8",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [],
    name: "decimals",
    outputs: [
      {
        internalType: "uint8",
        name: "",
        type: "uint8",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "latestRoundData",
    outputs: [
      {
        internalType: "uint80",
        name: "roundId",
        type: "uint80",
      },
      {
        internalType: "int256",
        name: "answer",
        type: "int256",
      },
      {
        internalType: "uint256",
        name: "startedAt",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "updatedAt",
        type: "uint256",
      },
      {
        internalType: "uint80",
        name: "answeredInRound",
        type: "uint80",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "int256",
        name: "answer_",
        type: "int256",
      },
      {
        internalType: "uint256",
        name: "updatedAt_",
        type: "uint256",
      },
    ],
    name: "setRoundData",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

const _bytecode =
  "0x60a03461008b57601f61021b38819003918201601f19168301916001600160401b038311848410176100905780849260209460405283398101031261008b575160ff8116810361008b576080526001808060501b031981816000541617600055600082554260025542600355600454161760045560405161017490816100a782396080518161011a0152f35b600080fd5b634e487b7160e01b600052604160045260246000fdfe60808060405260048036101561001457600080fd5b600091823560e01c908163313ce567146101015750806362cbca24146100955763feaf968c1461004357600080fd5b3461009157816003193601126100915760a09169ffffffffffffffffffff80915416916001549160025490600354925416926040519485526020850152604084015260608301526080820152f35b5080fd5b503461009157604036600319011261009157815469ffffffffffffffffffff6001818316018181116100ee5716908169ffffffffffffffffffff1980921617845582356001554260025560243560035582541617905580f35b634e487b7160e01b855260118452602485fd5b83903461009157816003193601126100915760209060ff7f0000000000000000000000000000000000000000000000000000000000000000168152f3fea26469706673582212200bdc6f249893b11211978a52efdfb318b755326647e1b76c6d62fdbbab69635364736f6c63430008140033";

type MockAggregatorV3ConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: MockAggregatorV3ConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class MockAggregatorV3__factory extends ContractFactory {
  constructor(...args: MockAggregatorV3ConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    feedDecimals: BigNumberish,
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(feedDecimals, overrides || {});
  }
  override deploy(
    feedDecimals: BigNumberish,
    overrides?: NonPayableOverrides & { from?: string }
  ) {
    return super.deploy(feedDecimals, overrides || {}) as Promise<
      MockAggregatorV3 & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): MockAggregatorV3__factory {
    return super.connect(runner) as MockAggregatorV3__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): MockAggregatorV3Interface {
    return new Interface(_abi) as MockAggregatorV3Interface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): MockAggregatorV3 {
    return new Contract(address, _abi, runner) as unknown as MockAggregatorV3;
  }
}
