/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export declare namespace AethelredTypes {
  export type BridgeTransferStruct = {
    nonce: BigNumberish;
    sender: AddressLike;
    recipient: AddressLike;
    token: AddressLike;
    amount: BigNumberish;
    sourceChainId: BigNumberish;
    destChainId: BigNumberish;
    status: BigNumberish;
    initiatedAt: BigNumberish;
  };

  export type BridgeTransferStructOutput = [
    nonce: bigint,
    sender: string,
    recipient: string,
    token: string,
    amount: bigint,
    sourceChainId: bigint,
    destChainId: bigint,
    status: bigint,
    initiatedAt: bigint
  ] & {
    nonce: bigint;
    sender: string;
    recipient: string;
    token: string;
    amount: bigint;
    sourceChainId: bigint;
    destChainId: bigint;
    status: bigint;
    initiatedAt: bigint;
  };
}

export interface IAethelredBridgeInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "cancelDeposit"
      | "cancelDeposit(uint256)"
      | "challengeDeadline"
      | "challengeDeadline(uint256)"
      | "challengeWithdrawal"
      | "challengeWithdrawal(uint256,bytes)"
      | "claimWithdrawal"
      | "claimWithdrawal(uint256)"
      | "currentNonce"
      | "currentNonce()"
      | "depositERC20"
      | "depositERC20(address,uint256,address)"
      | "depositETH"
      | "depositETH(address)"
      | "getTransfer"
      | "getTransfer(uint256)"
      | "isTokenWhitelisted"
      | "isTokenWhitelisted(address)"
      | "remainingDepositCapacity"
      | "remainingDepositCapacity()"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "Deposited"
      | "Deposited(uint256,address,address,uint256,uint256,address)"
      | "TransferChallenged"
      | "TransferChallenged(uint256,address,bytes)"
      | "WithdrawalFinalized"
      | "WithdrawalFinalized(uint256,address,address,uint256)"
      | "WithdrawalProposed"
      | "WithdrawalProposed(uint256,address,uint256,uint256)"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "cancelDeposit",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelDeposit(uint256)",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "challengeDeadline",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "challengeDeadline(uint256)",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "challengeWithdrawal",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "challengeWithdrawal(uint256,bytes)",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "claimWithdrawal",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claimWithdrawal(uint256)",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "currentNonce",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "currentNonce()",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "depositERC20",
    values: [AddressLike, BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "depositERC20(address,uint256,address)",
    values: [AddressLike, BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "depositETH",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "depositETH(address)",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTransfer",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTransfer(uint256)",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isTokenWhitelisted",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isTokenWhitelisted(address)",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "remainingDepositCapacity",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "remainingDepositCapacity()",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "cancelDeposit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelDeposit(uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "challengeDeadline",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "challengeDeadline(uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "challengeWithdrawal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "challengeWithdrawal(uint256,bytes)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimWithdrawal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimWithdrawal(uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "currentNonce",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "currentNonce()",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositERC20",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositERC20(address,uint256,address)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "depositETH", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "depositETH(address)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTransfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTransfer(uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isTokenWhitelisted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isTokenWhitelisted(address)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "remainingDepositCapacity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "remainingDepositCapacity()",
    data: BytesLike
  ): Result;
}

export namespace DepositedEvent {
  export type InputTuple = [
    nonce: BigNumberish,
    sender: AddressLike,
    token: AddressLike,
    amount: BigNumberish,
    destChainId: BigNumberish,
    recipient: AddressLike
  ];
  export type OutputTuple = [
    nonce: bigint,
    sender: string,
    token: string,
    amount: bigint,
    destChainId: bigint,
    recipient: string
  ];
  export interface OutputObject {
    nonce: bigint;
    sender: string;
    token: string;
    amount: bigint;
    destChainId: bigint;
    recipient: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransferChallengedEvent {
  export type InputTuple = [
    nonce: BigNumberish,
    challenger: AddressLike,
    reason: BytesLike
  ];
  export type OutputTuple = [nonce: bigint, challenger: string, reason: string];
  export interface OutputObject {
    nonce: bigint;
    challenger: string;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawalFinalizedEvent {
  export type InputTuple = [
    nonce: BigNumberish,
    recipient: AddressLike,
    token: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    nonce: bigint,
    recipient: string,
    token: string,
    amount: bigint
  ];
  export interface OutputObject {
    nonce: bigint;
    recipient: string;
    token: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawalProposedEvent {
  export type InputTuple = [
    nonce: BigNumberish,
    recipient: AddressLike,
    amount: BigNumberish,
    challengeDeadline: BigNumberish
  ];
  export type OutputTuple = [
    nonce: bigint,
    recipient: string,
    amount: bigint,
    challengeDeadline: bigint
  ];
  export interface OutputObject {
    nonce: bigint;
    recipient: string;
    amount: bigint;
    challengeDeadline: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IAethelredBridge extends BaseContract {
  connect(runner?: ContractRunner | null): IAethelredBridge;
  waitForDeployment(): Promise<this>;

  interface: IAethelredBridgeInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  cancelDeposit: TypedContractMethod<
    [nonce: BigNumberish],
    [void],
    "nonpayable"
  >;

  "cancelDeposit(uint256)": TypedContractMethod<
    [nonce: BigNumberish],
    [void],
    "nonpayable"
  >;

  challengeDeadline: TypedContractMethod<
    [nonce: BigNumberish],
    [bigint],
    "view"
  >;

  "challengeDeadline(uint256)": TypedContractMethod<
    [nonce: BigNumberish],
    [bigint],
    "view"
  >;

  challengeWithdrawal: TypedContractMethod<
    [nonce: BigNumberish, proof: BytesLike],
    [void],
    "nonpayable"
  >;

  "challengeWithdrawal(uint256,bytes)": TypedContractMethod<
    [nonce: BigNumberish, proof: BytesLike],
    [void],
    "nonpayable"
  >;

  claimWithdrawal: TypedContractMethod<
    [nonce: BigNumberish],
    [void],
    "nonpayable"
  >;

  "claimWithdrawal(uint256)": TypedContractMethod<
    [nonce: BigNumberish],
    [void],
    "nonpayable"
  >;

  currentNonce: TypedContractMethod<[], [bigint], "view">;

  "currentNonce()": TypedContractMethod<[], [bigint], "view">;

  depositERC20: TypedContractMethod<
    [token: AddressLike, amount: BigNumberish, recipient: AddressLike],
    [bigint],
    "nonpayable"
  >;

  "depositERC20(address,uint256,address)": TypedContractMethod<
    [token: AddressLike, amount: BigNumberish, recipient: AddressLike],
    [bigint],
    "nonpayable"
  >;

  depositETH: TypedContractMethod<
    [recipient: AddressLike],
    [bigint],
    "payable"
  >;

  "depositETH(address)": TypedContractMethod<
    [recipient: AddressLike],
    [bigint],
    "payable"
  >;

  getTransfer: TypedContractMethod<
    [nonce: BigNumberish],
    [AethelredTypes.BridgeTransferStructOutput],
    "view"
  >;

  "getTransfer(uint256)": TypedContractMethod<
    [nonce: BigNumberish],
    [AethelredTypes.BridgeTransferStructOutput],
    "view"
  >;

  isTokenWhitelisted: TypedContractMethod<
    [token: AddressLike],
    [boolean],
    "view"
  >;

  "isTokenWhitelisted(address)": TypedContractMethod<
    [token: AddressLike],
    [boolean],
    "view"
  >;

  remainingDepositCapacity: TypedContractMethod<[], [bigint], "view">;

  "remainingDepositCapacity()": TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "cancelDeposit"
  ): TypedContractMethod<[nonce: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "cancelDeposit(uint256)"
  ): TypedContractMethod<[nonce: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "challengeDeadline"
  ): TypedContractMethod<[nonce: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "challengeDeadline(uint256)"
  ): TypedContractMethod<[nonce: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "challengeWithdrawal"
  ): TypedContractMethod<
    [nonce: BigNumberish, proof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "challengeWithdrawal(uint256,bytes)"
  ): TypedContractMethod<
    [nonce: BigNumberish, proof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "claimWithdrawal"
  ): TypedContractMethod<[nonce: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimWithdrawal(uint256)"
  ): TypedContractMethod<[nonce: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "currentNonce"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "currentNonce()"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "depositERC20"
  ): TypedContractMethod<
    [token: AddressLike, amount: BigNumberish, recipient: AddressLike],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "depositERC20(address,uint256,address)"
  ): TypedContractMethod<
    [token: AddressLike, amount: BigNumberish, recipient: AddressLike],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "depositETH"
  ): TypedContractMethod<[recipient: AddressLike], [bigint], "payable">;
  getFunction(
    nameOrSignature: "depositETH(address)"
  ): TypedContractMethod<[recipient: AddressLike], [bigint], "payable">;
  getFunction(
    nameOrSignature: "getTransfer"
  ): TypedContractMethod<
    [nonce: BigNumberish],
    [AethelredTypes.BridgeTransferStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTransfer(uint256)"
  ): TypedContractMethod<
    [nonce: BigNumberish],
    [AethelredTypes.BridgeTransferStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "isTokenWhitelisted"
  ): TypedContractMethod<[token: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isTokenWhitelisted(address)"
  ): TypedContractMethod<[token: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "remainingDepositCapacity"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "remainingDepositCapacity()"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "Deposited"
  ): TypedContractEvent<
    DepositedEvent.InputTuple,
    DepositedEvent.OutputTuple,
    DepositedEvent.OutputObject
  >;
  getEvent(
    key: "Deposited(uint256,address,address,uint256,uint256,address)"
  ): TypedContractEvent<
    Deposited_uint256_address_address_uint256_uint256_address_Event.InputTuple,
    Deposited_uint256_address_address_uint256_uint256_address_Event.OutputTuple,
    Deposited_uint256_address_address_uint256_uint256_address_Event.OutputObject
  >;
  getEvent(
    key: "TransferChallenged"
  ): TypedContractEvent<
    TransferChallengedEvent.InputTuple,
    TransferChallengedEvent.OutputTuple,
    TransferChallengedEvent.OutputObject
  >;
  getEvent(
    key: "TransferChallenged(uint256,address,bytes)"
  ): TypedContractEvent<
    TransferChallenged_uint256_address_bytes_Event.InputTuple,
    TransferChallenged_uint256_address_bytes_Event.OutputTuple,
    TransferChallenged_uint256_address_bytes_Event.OutputObject
  >;
  getEvent(
    key: "WithdrawalFinalized"
  ): TypedContractEvent<
    WithdrawalFinalizedEvent.InputTuple,
    WithdrawalFinalizedEvent.OutputTuple,
    WithdrawalFinalizedEvent.OutputObject
  >;
  getEvent(
    key: "WithdrawalFinalized(uint256,address,address,uint256)"
  ): TypedContractEvent<
    WithdrawalFinalized_uint256_address_address_uint256_Event.InputTuple,
    WithdrawalFinalized_uint256_address_address_uint256_Event.OutputTuple,
    WithdrawalFinalized_uint256_address_address_uint256_Event.OutputObject
  >;
  getEvent(
    key: "WithdrawalProposed"
  ): TypedContractEvent<
    WithdrawalProposedEvent.InputTuple,
    WithdrawalProposedEvent.OutputTuple,
    WithdrawalProposedEvent.OutputObject
  >;
  getEvent(
    key: "WithdrawalProposed(uint256,address,uint256,uint256)"
  ): TypedContractEvent<
    WithdrawalProposed_uint256_address_uint256_uint256_Event.InputTuple,
    WithdrawalProposed_uint256_address_uint256_uint256_Event.OutputTuple,
    WithdrawalProposed_uint256_address_uint256_uint256_Event.OutputObject
  >;

  filters: {
    "Deposited(uint256,address,address,uint256,uint256,address)": TypedContractEvent<
      DepositedEvent.InputTuple,
      DepositedEvent.OutputTuple,
      DepositedEvent.OutputObject
    >;
    Deposited: TypedContractEvent<
      DepositedEvent.InputTuple,
      DepositedEvent.OutputTuple,
      DepositedEvent.OutputObject
    >;

    "TransferChallenged(uint256,address,bytes)": TypedContractEvent<
      TransferChallengedEvent.InputTuple,
      TransferChallengedEvent.OutputTuple,
      TransferChallengedEvent.OutputObject
    >;
    TransferChallenged: TypedContractEvent<
      TransferChallengedEvent.InputTuple,
      TransferChallengedEvent.OutputTuple,
      TransferChallengedEvent.OutputObject
    >;

    "WithdrawalFinalized(uint256,address,address,uint256)": TypedContractEvent<
      WithdrawalFinalizedEvent.InputTuple,
      WithdrawalFinalizedEvent.OutputTuple,
      WithdrawalFinalizedEvent.OutputObject
    >;
    WithdrawalFinalized: TypedContractEvent<
      WithdrawalFinalizedEvent.InputTuple,
      WithdrawalFinalizedEvent.OutputTuple,
      WithdrawalFinalizedEvent.OutputObject
    >;

    "WithdrawalProposed(uint256,address,uint256,uint256)": TypedContractEvent<
      WithdrawalProposedEvent.InputTuple,
      WithdrawalProposedEvent.OutputTuple,
      WithdrawalProposedEvent.OutputObject
    >;
    WithdrawalProposed: TypedContractEvent<
      WithdrawalProposedEvent.InputTuple,
      WithdrawalProposedEvent.OutputTuple,
      WithdrawalProposedEvent.OutputObject
    >;
  };
}
