/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export declare namespace AethelredTypes {
  export type TEEAttestationStruct = {
    validator: AddressLike;
    platform: BigNumberish;
    measurement: BytesLike;
    quoteHash: BytesLike;
    outputHash: BytesLike;
    timestamp: BigNumberish;
  };

  export type TEEAttestationStructOutput = [
    validator: string,
    platform: bigint,
    measurement: string,
    quoteHash: string,
    outputHash: string,
    timestamp: bigint
  ] & {
    validator: string;
    platform: bigint;
    measurement: string;
    quoteHash: string;
    outputHash: string;
    timestamp: bigint;
  };

  export type SealStruct = {
    sealId: BytesLike;
    jobId: BytesLike;
    modelCommitment: BytesLike;
    inputCommitment: BytesLike;
    outputCommitment: BytesLike;
    status: BigNumberish;
    verificationType: BigNumberish;
    attestationCount: BigNumberish;
    totalValidators: BigNumberish;
    consensusReached: boolean;
    l1BlockHeight: BigNumberish;
    timestamp: BigNumberish;
  };

  export type SealStructOutput = [
    sealId: string,
    jobId: string,
    modelCommitment: string,
    inputCommitment: string,
    outputCommitment: string,
    status: bigint,
    verificationType: bigint,
    attestationCount: bigint,
    totalValidators: bigint,
    consensusReached: boolean,
    l1BlockHeight: bigint,
    timestamp: bigint
  ] & {
    sealId: string;
    jobId: string;
    modelCommitment: string;
    inputCommitment: string;
    outputCommitment: string;
    status: bigint;
    verificationType: bigint;
    attestationCount: bigint;
    totalValidators: bigint;
    consensusReached: boolean;
    l1BlockHeight: bigint;
    timestamp: bigint;
  };
}

export interface IAethelredOracleInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getAttestations"
      | "getAttestations(bytes32)"
      | "getModelInfo"
      | "getModelInfo(string)"
      | "getOutputCommitment"
      | "getOutputCommitment(bytes32)"
      | "getResult"
      | "getResult(bytes32)"
      | "getSeal"
      | "getSeal(bytes32)"
      | "getSealByJobId"
      | "getSealByJobId(bytes32)"
      | "hasResult"
      | "hasResult(bytes32)"
      | "verifySeal"
      | "verifySeal(bytes32)"
      | "verifySealWithOutput"
      | "verifySealWithOutput(bytes32,bytes32)"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ResultPosted"
      | "ResultPosted(bytes32,bytes32,bytes32)"
      | "SealStatusUpdated"
      | "SealStatusUpdated(bytes32,uint8,uint8)"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "getAttestations",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAttestations(bytes32)",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getModelInfo",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getModelInfo(string)",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getOutputCommitment",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getOutputCommitment(bytes32)",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getResult",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getResult(bytes32)",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "getSeal", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "getSeal(bytes32)",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getSealByJobId",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getSealByJobId(bytes32)",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasResult",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasResult(bytes32)",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifySeal",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifySeal(bytes32)",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifySealWithOutput",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifySealWithOutput(bytes32,bytes32)",
    values: [BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "getAttestations",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAttestations(bytes32)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getModelInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getModelInfo(string)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getOutputCommitment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getOutputCommitment(bytes32)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getResult", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getResult(bytes32)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getSeal", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getSeal(bytes32)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSealByJobId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSealByJobId(bytes32)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hasResult", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "hasResult(bytes32)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "verifySeal", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "verifySeal(bytes32)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifySealWithOutput",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifySealWithOutput(bytes32,bytes32)",
    data: BytesLike
  ): Result;
}

export namespace ResultPostedEvent {
  export type InputTuple = [
    jobId: BytesLike,
    sealId: BytesLike,
    outputCommitment: BytesLike
  ];
  export type OutputTuple = [
    jobId: string,
    sealId: string,
    outputCommitment: string
  ];
  export interface OutputObject {
    jobId: string;
    sealId: string;
    outputCommitment: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SealStatusUpdatedEvent {
  export type InputTuple = [
    sealId: BytesLike,
    oldStatus: BigNumberish,
    newStatus: BigNumberish
  ];
  export type OutputTuple = [
    sealId: string,
    oldStatus: bigint,
    newStatus: bigint
  ];
  export interface OutputObject {
    sealId: string;
    oldStatus: bigint;
    newStatus: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IAethelredOracle extends BaseContract {
  connect(runner?: ContractRunner | null): IAethelredOracle;
  waitForDeployment(): Promise<this>;

  interface: IAethelredOracleInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getAttestations: TypedContractMethod<
    [sealId: BytesLike],
    [AethelredTypes.TEEAttestationStructOutput[]],
    "view"
  >;

  "getAttestations(bytes32)": TypedContractMethod<
    [sealId: BytesLike],
    [AethelredTypes.TEEAttestationStructOutput[]],
    "view"
  >;

  getModelInfo: TypedContractMethod<
    [modelId: string],
    [[string, string] & { modelCommitment: string; version: string }],
    "view"
  >;

  "getModelInfo(string)": TypedContractMethod<
    [modelId: string],
    [[string, string] & { modelCommitment: string; version: string }],
    "view"
  >;

  getOutputCommitment: TypedContractMethod<
    [jobId: BytesLike],
    [[string, boolean] & { outputCommitment: string; valid: boolean }],
    "view"
  >;

  "getOutputCommitment(bytes32)": TypedContractMethod<
    [jobId: BytesLike],
    [[string, boolean] & { outputCommitment: string; valid: boolean }],
    "view"
  >;

  getResult: TypedContractMethod<
    [jobId: BytesLike],
    [[string, boolean] & { result: string; valid: boolean }],
    "view"
  >;

  "getResult(bytes32)": TypedContractMethod<
    [jobId: BytesLike],
    [[string, boolean] & { result: string; valid: boolean }],
    "view"
  >;

  getSeal: TypedContractMethod<
    [sealId: BytesLike],
    [AethelredTypes.SealStructOutput],
    "view"
  >;

  "getSeal(bytes32)": TypedContractMethod<
    [sealId: BytesLike],
    [AethelredTypes.SealStructOutput],
    "view"
  >;

  getSealByJobId: TypedContractMethod<
    [jobId: BytesLike],
    [AethelredTypes.SealStructOutput],
    "view"
  >;

  "getSealByJobId(bytes32)": TypedContractMethod<
    [jobId: BytesLike],
    [AethelredTypes.SealStructOutput],
    "view"
  >;

  hasResult: TypedContractMethod<[jobId: BytesLike], [boolean], "view">;

  "hasResult(bytes32)": TypedContractMethod<
    [jobId: BytesLike],
    [boolean],
    "view"
  >;

  verifySeal: TypedContractMethod<[sealId: BytesLike], [boolean], "view">;

  "verifySeal(bytes32)": TypedContractMethod<
    [sealId: BytesLike],
    [boolean],
    "view"
  >;

  verifySealWithOutput: TypedContractMethod<
    [sealId: BytesLike, outputCommitment: BytesLike],
    [boolean],
    "view"
  >;

  "verifySealWithOutput(bytes32,bytes32)": TypedContractMethod<
    [sealId: BytesLike, outputCommitment: BytesLike],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getAttestations"
  ): TypedContractMethod<
    [sealId: BytesLike],
    [AethelredTypes.TEEAttestationStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAttestations(bytes32)"
  ): TypedContractMethod<
    [sealId: BytesLike],
    [AethelredTypes.TEEAttestationStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getModelInfo"
  ): TypedContractMethod<
    [modelId: string],
    [[string, string] & { modelCommitment: string; version: string }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getModelInfo(string)"
  ): TypedContractMethod<
    [modelId: string],
    [[string, string] & { modelCommitment: string; version: string }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getOutputCommitment"
  ): TypedContractMethod<
    [jobId: BytesLike],
    [[string, boolean] & { outputCommitment: string; valid: boolean }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getOutputCommitment(bytes32)"
  ): TypedContractMethod<
    [jobId: BytesLike],
    [[string, boolean] & { outputCommitment: string; valid: boolean }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getResult"
  ): TypedContractMethod<
    [jobId: BytesLike],
    [[string, boolean] & { result: string; valid: boolean }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getResult(bytes32)"
  ): TypedContractMethod<
    [jobId: BytesLike],
    [[string, boolean] & { result: string; valid: boolean }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getSeal"
  ): TypedContractMethod<
    [sealId: BytesLike],
    [AethelredTypes.SealStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getSeal(bytes32)"
  ): TypedContractMethod<
    [sealId: BytesLike],
    [AethelredTypes.SealStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getSealByJobId"
  ): TypedContractMethod<
    [jobId: BytesLike],
    [AethelredTypes.SealStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getSealByJobId(bytes32)"
  ): TypedContractMethod<
    [jobId: BytesLike],
    [AethelredTypes.SealStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasResult"
  ): TypedContractMethod<[jobId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "hasResult(bytes32)"
  ): TypedContractMethod<[jobId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "verifySeal"
  ): TypedContractMethod<[sealId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "verifySeal(bytes32)"
  ): TypedContractMethod<[sealId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "verifySealWithOutput"
  ): TypedContractMethod<
    [sealId: BytesLike, outputCommitment: BytesLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "verifySealWithOutput(bytes32,bytes32)"
  ): TypedContractMethod<
    [sealId: BytesLike, outputCommitment: BytesLike],
    [boolean],
    "view"
  >;

  getEvent(
    key: "ResultPosted"
  ): TypedContractEvent<
    ResultPostedEvent.InputTuple,
    ResultPostedEvent.OutputTuple,
    ResultPostedEvent.OutputObject
  >;
  getEvent(
    key: "ResultPosted(bytes32,bytes32,bytes32)"
  ): TypedContractEvent<
    ResultPosted_bytes32_bytes32_bytes32_Event.InputTuple,
    ResultPosted_bytes32_bytes32_bytes32_Event.OutputTuple,
    ResultPosted_bytes32_bytes32_bytes32_Event.OutputObject
  >;
  getEvent(
    key: "SealStatusUpdated"
  ): TypedContractEvent<
    SealStatusUpdatedEvent.InputTuple,
    SealStatusUpdatedEvent.OutputTuple,
    SealStatusUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "SealStatusUpdated(bytes32,uint8,uint8)"
  ): TypedContractEvent<
    SealStatusUpdated_bytes32_uint8_uint8_Event.InputTuple,
    SealStatusUpdated_bytes32_uint8_uint8_Event.OutputTuple,
    SealStatusUpdated_bytes32_uint8_uint8_Event.OutputObject
  >;

  filters: {
    "ResultPosted(bytes32,bytes32,bytes32)": TypedContractEvent<
      ResultPostedEvent.InputTuple,
      ResultPostedEvent.OutputTuple,
      ResultPostedEvent.OutputObject
    >;
    ResultPosted: TypedContractEvent<
      ResultPostedEvent.InputTuple,
      ResultPostedEvent.OutputTuple,
      ResultPostedEvent.OutputObject
    >;

    "SealStatusUpdated(bytes32,uint8,uint8)": TypedContractEvent<
      SealStatusUpdatedEvent.InputTuple,
      SealStatusUpdatedEvent.OutputTuple,
      SealStatusUpdatedEvent.OutputObject
    >;
    SealStatusUpdated: TypedContractEvent<
      SealStatusUpdatedEvent.InputTuple,
      SealStatusUpdatedEvent.OutputTuple,
      SealStatusUpdatedEvent.OutputObject
    >;
  };
}
