/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as iAethelredTeeSol from "./IAethelredTEE.sol";
export type { iAethelredTeeSol };
export type { IAethelredBridge } from "./IAethelredBridge";
export type { IAethelredOracle } from "./IAethelredOracle";
export type { ISovereignCircuitBreaker } from "./ISovereignCircuitBreaker";
