/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface IInstitutionalBridgeGovernanceInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "auditorGovernanceKey"
      | "auditorGovernanceKey()"
      | "foundationGovernanceKey"
      | "foundationGovernanceKey()"
      | "guardianGovernanceKey"
      | "guardianGovernanceKey()"
      | "issuerGovernanceKey"
      | "issuerGovernanceKey()"
      | "issuerRecoveryGovernanceKey"
      | "issuerRecoveryGovernanceKey()"
      | "setGovernanceKeys"
      | "setGovernanceKeys(address,address,address)"
      | "setSovereignUnpauseKeys"
      | "setSovereignUnpauseKeys(address,address)"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "auditorGovernanceKey",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "auditorGovernanceKey()",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "foundationGovernanceKey",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "foundationGovernanceKey()",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "guardianGovernanceKey",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "guardianGovernanceKey()",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "issuerGovernanceKey",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "issuerGovernanceKey()",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "issuerRecoveryGovernanceKey",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "issuerRecoveryGovernanceKey()",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setGovernanceKeys",
    values: [AddressLike, AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setGovernanceKeys(address,address,address)",
    values: [AddressLike, AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setSovereignUnpauseKeys",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setSovereignUnpauseKeys(address,address)",
    values: [AddressLike, AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "auditorGovernanceKey",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "auditorGovernanceKey()",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "foundationGovernanceKey",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "foundationGovernanceKey()",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "guardianGovernanceKey",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "guardianGovernanceKey()",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "issuerGovernanceKey",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "issuerGovernanceKey()",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "issuerRecoveryGovernanceKey",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "issuerRecoveryGovernanceKey()",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setGovernanceKeys",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setGovernanceKeys(address,address,address)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setSovereignUnpauseKeys",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setSovereignUnpauseKeys(address,address)",
    data: BytesLike
  ): Result;
}

export interface IInstitutionalBridgeGovernance extends BaseContract {
  connect(runner?: ContractRunner | null): IInstitutionalBridgeGovernance;
  waitForDeployment(): Promise<this>;

  interface: IInstitutionalBridgeGovernanceInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  auditorGovernanceKey: TypedContractMethod<[], [string], "view">;

  "auditorGovernanceKey()": TypedContractMethod<[], [string], "view">;

  foundationGovernanceKey: TypedContractMethod<[], [string], "view">;

  "foundationGovernanceKey()": TypedContractMethod<[], [string], "view">;

  guardianGovernanceKey: TypedContractMethod<[], [string], "view">;

  "guardianGovernanceKey()": TypedContractMethod<[], [string], "view">;

  issuerGovernanceKey: TypedContractMethod<[], [string], "view">;

  "issuerGovernanceKey()": TypedContractMethod<[], [string], "view">;

  issuerRecoveryGovernanceKey: TypedContractMethod<[], [string], "view">;

  "issuerRecoveryGovernanceKey()": TypedContractMethod<[], [string], "view">;

  setGovernanceKeys: TypedContractMethod<
    [
      issuerKey: AddressLike,
      foundationKey: AddressLike,
      auditorKey: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  "setGovernanceKeys(address,address,address)": TypedContractMethod<
    [
      issuerKey: AddressLike,
      foundationKey: AddressLike,
      auditorKey: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  setSovereignUnpauseKeys: TypedContractMethod<
    [issuerRecoveryKey: AddressLike, guardianKey: AddressLike],
    [void],
    "nonpayable"
  >;

  "setSovereignUnpauseKeys(address,address)": TypedContractMethod<
    [issuerRecoveryKey: AddressLike, guardianKey: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "auditorGovernanceKey"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "auditorGovernanceKey()"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "foundationGovernanceKey"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "foundationGovernanceKey()"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "guardianGovernanceKey"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "guardianGovernanceKey()"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "issuerGovernanceKey"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "issuerGovernanceKey()"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "issuerRecoveryGovernanceKey"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "issuerRecoveryGovernanceKey()"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setGovernanceKeys"
  ): TypedContractMethod<
    [
      issuerKey: AddressLike,
      foundationKey: AddressLike,
      auditorKey: AddressLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setGovernanceKeys(address,address,address)"
  ): TypedContractMethod<
    [
      issuerKey: AddressLike,
      foundationKey: AddressLike,
      auditorKey: AddressLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setSovereignUnpauseKeys"
  ): TypedContractMethod<
    [issuerRecoveryKey: AddressLike, guardianKey: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setSovereignUnpauseKeys(address,address)"
  ): TypedContractMethod<
    [issuerRecoveryKey: AddressLike, guardianKey: AddressLike],
    [void],
    "nonpayable"
  >;

  filters: {};
}
