/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IInstitutionalBridgeGovernance } from "./IInstitutionalBridgeGovernance";
export type { SovereignGovernanceTimelock } from "./SovereignGovernanceTimelock";
