/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface SovereignGovernanceTimelockInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "CANCELLER_ROLE"
      | "CANCELLER_ROLE()"
      | "DEFAULT_ADMIN_ROLE"
      | "DEFAULT_ADMIN_ROLE()"
      | "EXECUTOR_ROLE"
      | "EXECUTOR_ROLE()"
      | "MIN_KEY_ROTATION_DELAY"
      | "MIN_KEY_ROTATION_DELAY()"
      | "PROPOSER_ROLE"
      | "PROPOSER_ROLE()"
      | "cancel"
      | "cancel(bytes32)"
      | "execute"
      | "execute(address,uint256,bytes,bytes32,bytes32)"
      | "executeBatch"
      | "executeBatch(address[],uint256[],bytes[],bytes32,bytes32)"
      | "executeKeyRotation"
      | "executeKeyRotation(bytes32)"
      | "getMinDelay"
      | "getMinDelay()"
      | "getOperationState"
      | "getOperationState(bytes32)"
      | "getRoleAdmin"
      | "getRoleAdmin(bytes32)"
      | "getTimestamp"
      | "getTimestamp(bytes32)"
      | "grantRole"
      | "grantRole(bytes32,address)"
      | "hasRole"
      | "hasRole(bytes32,address)"
      | "hashOperation"
      | "hashOperation(address,uint256,bytes,bytes32,bytes32)"
      | "hashOperationBatch"
      | "hashOperationBatch(address[],uint256[],bytes[],bytes32,bytes32)"
      | "isOperation"
      | "isOperation(bytes32)"
      | "isOperationDone"
      | "isOperationDone(bytes32)"
      | "isOperationPending"
      | "isOperationPending(bytes32)"
      | "isOperationReady"
      | "isOperationReady(bytes32)"
      | "onERC1155BatchReceived"
      | "onERC1155BatchReceived(address,address,uint256[],uint256[],bytes)"
      | "onERC1155Received"
      | "onERC1155Received(address,address,uint256,uint256,bytes)"
      | "onERC721Received"
      | "onERC721Received(address,address,uint256,bytes)"
      | "renounceRole"
      | "renounceRole(bytes32,address)"
      | "revokeRole"
      | "revokeRole(bytes32,address)"
      | "rotateKey"
      | "rotateKey(address,uint8,address,bytes32,bytes32,uint256,bytes,bytes)"
      | "rotationOperations"
      | "rotationOperations(bytes32)"
      | "schedule"
      | "schedule(address,uint256,bytes,bytes32,bytes32,uint256)"
      | "scheduleBatch"
      | "scheduleBatch(address[],uint256[],bytes[],bytes32,bytes32,uint256)"
      | "supportsInterface"
      | "supportsInterface(bytes4)"
      | "updateDelay"
      | "updateDelay(uint256)"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CallExecuted"
      | "CallExecuted(bytes32,uint256,address,uint256,bytes)"
      | "CallSalt"
      | "CallSalt(bytes32,bytes32)"
      | "CallScheduled"
      | "CallScheduled(bytes32,uint256,address,uint256,bytes,bytes32,uint256)"
      | "Cancelled"
      | "Cancelled(bytes32)"
      | "KeyRotationExecuted"
      | "KeyRotationExecuted(bytes32,address,address,address,address,address,address)"
      | "KeyRotationQueued"
      | "KeyRotationQueued(bytes32,address,uint8,address,uint256)"
      | "MinDelayChange"
      | "MinDelayChange(uint256,uint256)"
      | "RoleAdminChanged"
      | "RoleAdminChanged(bytes32,bytes32,bytes32)"
      | "RoleGranted"
      | "RoleGranted(bytes32,address,address)"
      | "RoleRevoked"
      | "RoleRevoked(bytes32,address,address)"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "CANCELLER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "CANCELLER_ROLE()",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE()",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "EXECUTOR_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "EXECUTOR_ROLE()",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MIN_KEY_ROTATION_DELAY",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MIN_KEY_ROTATION_DELAY()",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PROPOSER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PROPOSER_ROLE()",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "cancel", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "cancel(bytes32)",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "execute",
    values: [AddressLike, BigNumberish, BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "execute(address,uint256,bytes,bytes32,bytes32)",
    values: [AddressLike, BigNumberish, BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "executeBatch",
    values: [AddressLike[], BigNumberish[], BytesLike[], BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "executeBatch(address[],uint256[],bytes[],bytes32,bytes32)",
    values: [AddressLike[], BigNumberish[], BytesLike[], BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "executeKeyRotation",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "executeKeyRotation(bytes32)",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getMinDelay",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getMinDelay()",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getOperationState",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getOperationState(bytes32)",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin(bytes32)",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTimestamp",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTimestamp(bytes32)",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole(bytes32,address)",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole(bytes32,address)",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hashOperation",
    values: [AddressLike, BigNumberish, BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hashOperation(address,uint256,bytes,bytes32,bytes32)",
    values: [AddressLike, BigNumberish, BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hashOperationBatch",
    values: [AddressLike[], BigNumberish[], BytesLike[], BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hashOperationBatch(address[],uint256[],bytes[],bytes32,bytes32)",
    values: [AddressLike[], BigNumberish[], BytesLike[], BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isOperation",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isOperation(bytes32)",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isOperationDone",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isOperationDone(bytes32)",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isOperationPending",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isOperationPending(bytes32)",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isOperationReady",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isOperationReady(bytes32)",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "onERC1155BatchReceived",
    values: [
      AddressLike,
      AddressLike,
      BigNumberish[],
      BigNumberish[],
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "onERC1155BatchReceived(address,address,uint256[],uint256[],bytes)",
    values: [
      AddressLike,
      AddressLike,
      BigNumberish[],
      BigNumberish[],
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "onERC1155Received",
    values: [AddressLike, AddressLike, BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "onERC1155Received(address,address,uint256,uint256,bytes)",
    values: [AddressLike, AddressLike, BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "onERC721Received",
    values: [AddressLike, AddressLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "onERC721Received(address,address,uint256,bytes)",
    values: [AddressLike, AddressLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole(bytes32,address)",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole(bytes32,address)",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "rotateKey",
    values: [
      AddressLike,
      BigNumberish,
      AddressLike,
      BytesLike,
      BytesLike,
      BigNumberish,
      BytesLike,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "rotateKey(address,uint8,address,bytes32,bytes32,uint256,bytes,bytes)",
    values: [
      AddressLike,
      BigNumberish,
      AddressLike,
      BytesLike,
      BytesLike,
      BigNumberish,
      BytesLike,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "rotationOperations",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "rotationOperations(bytes32)",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "schedule",
    values: [
      AddressLike,
      BigNumberish,
      BytesLike,
      BytesLike,
      BytesLike,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "schedule(address,uint256,bytes,bytes32,bytes32,uint256)",
    values: [
      AddressLike,
      BigNumberish,
      BytesLike,
      BytesLike,
      BytesLike,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "scheduleBatch",
    values: [
      AddressLike[],
      BigNumberish[],
      BytesLike[],
      BytesLike,
      BytesLike,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "scheduleBatch(address[],uint256[],bytes[],bytes32,bytes32,uint256)",
    values: [
      AddressLike[],
      BigNumberish[],
      BytesLike[],
      BytesLike,
      BytesLike,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface(bytes4)",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateDelay",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateDelay(uint256)",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "CANCELLER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "CANCELLER_ROLE()",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE()",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "EXECUTOR_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "EXECUTOR_ROLE()",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MIN_KEY_ROTATION_DELAY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MIN_KEY_ROTATION_DELAY()",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PROPOSER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PROPOSER_ROLE()",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "cancel", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "cancel(bytes32)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "execute", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "execute(address,uint256,bytes,bytes32,bytes32)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeBatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeBatch(address[],uint256[],bytes[],bytes32,bytes32)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeKeyRotation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeKeyRotation(bytes32)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMinDelay",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMinDelay()",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getOperationState",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getOperationState(bytes32)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin(bytes32)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTimestamp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTimestamp(bytes32)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "grantRole(bytes32,address)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "hasRole(bytes32,address)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hashOperation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hashOperation(address,uint256,bytes,bytes32,bytes32)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hashOperationBatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hashOperationBatch(address[],uint256[],bytes[],bytes32,bytes32)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isOperation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isOperation(bytes32)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isOperationDone",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isOperationDone(bytes32)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isOperationPending",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isOperationPending(bytes32)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isOperationReady",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isOperationReady(bytes32)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "onERC1155BatchReceived",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "onERC1155BatchReceived(address,address,uint256[],uint256[],bytes)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "onERC1155Received",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "onERC1155Received(address,address,uint256,uint256,bytes)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "onERC721Received",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "onERC721Received(address,address,uint256,bytes)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole(bytes32,address)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "revokeRole(bytes32,address)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "rotateKey", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "rotateKey(address,uint8,address,bytes32,bytes32,uint256,bytes,bytes)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rotationOperations",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rotationOperations(bytes32)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "schedule", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "schedule(address,uint256,bytes,bytes32,bytes32,uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "scheduleBatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "scheduleBatch(address[],uint256[],bytes[],bytes32,bytes32,uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface(bytes4)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateDelay",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateDelay(uint256)",
    data: BytesLike
  ): Result;
}

export namespace CallExecutedEvent {
  export type InputTuple = [
    id: BytesLike,
    index: BigNumberish,
    target: AddressLike,
    value: BigNumberish,
    data: BytesLike
  ];
  export type OutputTuple = [
    id: string,
    index: bigint,
    target: string,
    value: bigint,
    data: string
  ];
  export interface OutputObject {
    id: string;
    index: bigint;
    target: string;
    value: bigint;
    data: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CallSaltEvent {
  export type InputTuple = [id: BytesLike, salt: BytesLike];
  export type OutputTuple = [id: string, salt: string];
  export interface OutputObject {
    id: string;
    salt: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CallScheduledEvent {
  export type InputTuple = [
    id: BytesLike,
    index: BigNumberish,
    target: AddressLike,
    value: BigNumberish,
    data: BytesLike,
    predecessor: BytesLike,
    delay: BigNumberish
  ];
  export type OutputTuple = [
    id: string,
    index: bigint,
    target: string,
    value: bigint,
    data: string,
    predecessor: string,
    delay: bigint
  ];
  export interface OutputObject {
    id: string;
    index: bigint;
    target: string;
    value: bigint;
    data: string;
    predecessor: string;
    delay: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CancelledEvent {
  export type InputTuple = [id: BytesLike];
  export type OutputTuple = [id: string];
  export interface OutputObject {
    id: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace KeyRotationExecutedEvent {
  export type InputTuple = [
    operationId: BytesLike,
    bridge: AddressLike,
    issuerKey: AddressLike,
    issuerRecoveryKey: AddressLike,
    foundationKey: AddressLike,
    auditorKey: AddressLike,
    guardianKey: AddressLike
  ];
  export type OutputTuple = [
    operationId: string,
    bridge: string,
    issuerKey: string,
    issuerRecoveryKey: string,
    foundationKey: string,
    auditorKey: string,
    guardianKey: string
  ];
  export interface OutputObject {
    operationId: string;
    bridge: string;
    issuerKey: string;
    issuerRecoveryKey: string;
    foundationKey: string;
    auditorKey: string;
    guardianKey: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace KeyRotationQueuedEvent {
  export type InputTuple = [
    operationId: BytesLike,
    bridge: AddressLike,
    keyType: BigNumberish,
    newKey: AddressLike,
    executeAfter: BigNumberish
  ];
  export type OutputTuple = [
    operationId: string,
    bridge: string,
    keyType: bigint,
    newKey: string,
    executeAfter: bigint
  ];
  export interface OutputObject {
    operationId: string;
    bridge: string;
    keyType: bigint;
    newKey: string;
    executeAfter: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MinDelayChangeEvent {
  export type InputTuple = [
    oldDuration: BigNumberish,
    newDuration: BigNumberish
  ];
  export type OutputTuple = [oldDuration: bigint, newDuration: bigint];
  export interface OutputObject {
    oldDuration: bigint;
    newDuration: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SovereignGovernanceTimelock extends BaseContract {
  connect(runner?: ContractRunner | null): SovereignGovernanceTimelock;
  waitForDeployment(): Promise<this>;

  interface: SovereignGovernanceTimelockInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  CANCELLER_ROLE: TypedContractMethod<[], [string], "view">;

  "CANCELLER_ROLE()": TypedContractMethod<[], [string], "view">;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  "DEFAULT_ADMIN_ROLE()": TypedContractMethod<[], [string], "view">;

  EXECUTOR_ROLE: TypedContractMethod<[], [string], "view">;

  "EXECUTOR_ROLE()": TypedContractMethod<[], [string], "view">;

  MIN_KEY_ROTATION_DELAY: TypedContractMethod<[], [bigint], "view">;

  "MIN_KEY_ROTATION_DELAY()": TypedContractMethod<[], [bigint], "view">;

  PROPOSER_ROLE: TypedContractMethod<[], [string], "view">;

  "PROPOSER_ROLE()": TypedContractMethod<[], [string], "view">;

  cancel: TypedContractMethod<[id: BytesLike], [void], "nonpayable">;

  "cancel(bytes32)": TypedContractMethod<[id: BytesLike], [void], "nonpayable">;

  execute: TypedContractMethod<
    [
      target: AddressLike,
      value: BigNumberish,
      payload: BytesLike,
      predecessor: BytesLike,
      salt: BytesLike
    ],
    [void],
    "payable"
  >;

  "execute(address,uint256,bytes,bytes32,bytes32)": TypedContractMethod<
    [
      target: AddressLike,
      value: BigNumberish,
      payload: BytesLike,
      predecessor: BytesLike,
      salt: BytesLike
    ],
    [void],
    "payable"
  >;

  executeBatch: TypedContractMethod<
    [
      targets: AddressLike[],
      values: BigNumberish[],
      payloads: BytesLike[],
      predecessor: BytesLike,
      salt: BytesLike
    ],
    [void],
    "payable"
  >;

  "executeBatch(address[],uint256[],bytes[],bytes32,bytes32)": TypedContractMethod<
    [
      targets: AddressLike[],
      values: BigNumberish[],
      payloads: BytesLike[],
      predecessor: BytesLike,
      salt: BytesLike
    ],
    [void],
    "payable"
  >;

  executeKeyRotation: TypedContractMethod<
    [operationId: BytesLike],
    [void],
    "nonpayable"
  >;

  "executeKeyRotation(bytes32)": TypedContractMethod<
    [operationId: BytesLike],
    [void],
    "nonpayable"
  >;

  getMinDelay: TypedContractMethod<[], [bigint], "view">;

  "getMinDelay()": TypedContractMethod<[], [bigint], "view">;

  getOperationState: TypedContractMethod<[id: BytesLike], [bigint], "view">;

  "getOperationState(bytes32)": TypedContractMethod<
    [id: BytesLike],
    [bigint],
    "view"
  >;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  "getRoleAdmin(bytes32)": TypedContractMethod<
    [role: BytesLike],
    [string],
    "view"
  >;

  getTimestamp: TypedContractMethod<[id: BytesLike], [bigint], "view">;

  "getTimestamp(bytes32)": TypedContractMethod<
    [id: BytesLike],
    [bigint],
    "view"
  >;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  "grantRole(bytes32,address)": TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  "hasRole(bytes32,address)": TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  hashOperation: TypedContractMethod<
    [
      target: AddressLike,
      value: BigNumberish,
      data: BytesLike,
      predecessor: BytesLike,
      salt: BytesLike
    ],
    [string],
    "view"
  >;

  "hashOperation(address,uint256,bytes,bytes32,bytes32)": TypedContractMethod<
    [
      target: AddressLike,
      value: BigNumberish,
      data: BytesLike,
      predecessor: BytesLike,
      salt: BytesLike
    ],
    [string],
    "view"
  >;

  hashOperationBatch: TypedContractMethod<
    [
      targets: AddressLike[],
      values: BigNumberish[],
      payloads: BytesLike[],
      predecessor: BytesLike,
      salt: BytesLike
    ],
    [string],
    "view"
  >;

  "hashOperationBatch(address[],uint256[],bytes[],bytes32,bytes32)": TypedContractMethod<
    [
      targets: AddressLike[],
      values: BigNumberish[],
      payloads: BytesLike[],
      predecessor: BytesLike,
      salt: BytesLike
    ],
    [string],
    "view"
  >;

  isOperation: TypedContractMethod<[id: BytesLike], [boolean], "view">;

  "isOperation(bytes32)": TypedContractMethod<
    [id: BytesLike],
    [boolean],
    "view"
  >;

  isOperationDone: TypedContractMethod<[id: BytesLike], [boolean], "view">;

  "isOperationDone(bytes32)": TypedContractMethod<
    [id: BytesLike],
    [boolean],
    "view"
  >;

  isOperationPending: TypedContractMethod<[id: BytesLike], [boolean], "view">;

  "isOperationPending(bytes32)": TypedContractMethod<
    [id: BytesLike],
    [boolean],
    "view"
  >;

  isOperationReady: TypedContractMethod<[id: BytesLike], [boolean], "view">;

  "isOperationReady(bytes32)": TypedContractMethod<
    [id: BytesLike],
    [boolean],
    "view"
  >;

  onERC1155BatchReceived: TypedContractMethod<
    [
      arg0: AddressLike,
      arg1: AddressLike,
      arg2: BigNumberish[],
      arg3: BigNumberish[],
      arg4: BytesLike
    ],
    [string],
    "nonpayable"
  >;

  "onERC1155BatchReceived(address,address,uint256[],uint256[],bytes)": TypedContractMethod<
    [
      arg0: AddressLike,
      arg1: AddressLike,
      arg2: BigNumberish[],
      arg3: BigNumberish[],
      arg4: BytesLike
    ],
    [string],
    "nonpayable"
  >;

  onERC1155Received: TypedContractMethod<
    [
      arg0: AddressLike,
      arg1: AddressLike,
      arg2: BigNumberish,
      arg3: BigNumberish,
      arg4: BytesLike
    ],
    [string],
    "nonpayable"
  >;

  "onERC1155Received(address,address,uint256,uint256,bytes)": TypedContractMethod<
    [
      arg0: AddressLike,
      arg1: AddressLike,
      arg2: BigNumberish,
      arg3: BigNumberish,
      arg4: BytesLike
    ],
    [string],
    "nonpayable"
  >;

  onERC721Received: TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike, arg2: BigNumberish, arg3: BytesLike],
    [string],
    "nonpayable"
  >;

  "onERC721Received(address,address,uint256,bytes)": TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike, arg2: BigNumberish, arg3: BytesLike],
    [string],
    "nonpayable"
  >;

  renounceRole: TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;

  "renounceRole(bytes32,address)": TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  "revokeRole(bytes32,address)": TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  rotateKey: TypedContractMethod<
    [
      bridge: AddressLike,
      keyType: BigNumberish,
      newKey: AddressLike,
      predecessor: BytesLike,
      salt: BytesLike,
      deadline: BigNumberish,
      issuerSignature: BytesLike,
      foundationSignature: BytesLike
    ],
    [string],
    "nonpayable"
  >;

  "rotateKey(address,uint8,address,bytes32,bytes32,uint256,bytes,bytes)": TypedContractMethod<
    [
      bridge: AddressLike,
      keyType: BigNumberish,
      newKey: AddressLike,
      predecessor: BytesLike,
      salt: BytesLike,
      deadline: BigNumberish,
      issuerSignature: BytesLike,
      foundationSignature: BytesLike
    ],
    [string],
    "nonpayable"
  >;

  rotationOperations: TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        boolean,
        boolean,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        boolean
      ] & {
        exists: boolean;
        executed: boolean;
        bridge: string;
        newIssuerKey: string;
        newIssuerRecoveryKey: string;
        newFoundationKey: string;
        newAuditorKey: string;
        newGuardianKey: string;
        predecessor: string;
        salt: string;
        usePrimaryKeySetter: boolean;
      }
    ],
    "view"
  >;

  "rotationOperations(bytes32)": TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        boolean,
        boolean,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        boolean
      ] & {
        exists: boolean;
        executed: boolean;
        bridge: string;
        newIssuerKey: string;
        newIssuerRecoveryKey: string;
        newFoundationKey: string;
        newAuditorKey: string;
        newGuardianKey: string;
        predecessor: string;
        salt: string;
        usePrimaryKeySetter: boolean;
      }
    ],
    "view"
  >;

  schedule: TypedContractMethod<
    [
      target: AddressLike,
      value: BigNumberish,
      data: BytesLike,
      predecessor: BytesLike,
      salt: BytesLike,
      delay: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  "schedule(address,uint256,bytes,bytes32,bytes32,uint256)": TypedContractMethod<
    [
      target: AddressLike,
      value: BigNumberish,
      data: BytesLike,
      predecessor: BytesLike,
      salt: BytesLike,
      delay: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  scheduleBatch: TypedContractMethod<
    [
      targets: AddressLike[],
      values: BigNumberish[],
      payloads: BytesLike[],
      predecessor: BytesLike,
      salt: BytesLike,
      delay: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  "scheduleBatch(address[],uint256[],bytes[],bytes32,bytes32,uint256)": TypedContractMethod<
    [
      targets: AddressLike[],
      values: BigNumberish[],
      payloads: BytesLike[],
      predecessor: BytesLike,
      salt: BytesLike,
      delay: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  "supportsInterface(bytes4)": TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  updateDelay: TypedContractMethod<
    [newDelay: BigNumberish],
    [void],
    "nonpayable"
  >;

  "updateDelay(uint256)": TypedContractMethod<
    [newDelay: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "CANCELLER_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "CANCELLER_ROLE()"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE()"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "EXECUTOR_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "EXECUTOR_ROLE()"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "MIN_KEY_ROTATION_DELAY"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_KEY_ROTATION_DELAY()"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PROPOSER_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "PROPOSER_ROLE()"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "cancel"
  ): TypedContractMethod<[id: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "cancel(bytes32)"
  ): TypedContractMethod<[id: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "execute"
  ): TypedContractMethod<
    [
      target: AddressLike,
      value: BigNumberish,
      payload: BytesLike,
      predecessor: BytesLike,
      salt: BytesLike
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "execute(address,uint256,bytes,bytes32,bytes32)"
  ): TypedContractMethod<
    [
      target: AddressLike,
      value: BigNumberish,
      payload: BytesLike,
      predecessor: BytesLike,
      salt: BytesLike
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "executeBatch"
  ): TypedContractMethod<
    [
      targets: AddressLike[],
      values: BigNumberish[],
      payloads: BytesLike[],
      predecessor: BytesLike,
      salt: BytesLike
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "executeBatch(address[],uint256[],bytes[],bytes32,bytes32)"
  ): TypedContractMethod<
    [
      targets: AddressLike[],
      values: BigNumberish[],
      payloads: BytesLike[],
      predecessor: BytesLike,
      salt: BytesLike
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "executeKeyRotation"
  ): TypedContractMethod<[operationId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "executeKeyRotation(bytes32)"
  ): TypedContractMethod<[operationId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getMinDelay"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getMinDelay()"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getOperationState"
  ): TypedContractMethod<[id: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getOperationState(bytes32)"
  ): TypedContractMethod<[id: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "getRoleAdmin(bytes32)"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "getTimestamp"
  ): TypedContractMethod<[id: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getTimestamp(bytes32)"
  ): TypedContractMethod<[id: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "grantRole(bytes32,address)"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasRole(bytes32,address)"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "hashOperation"
  ): TypedContractMethod<
    [
      target: AddressLike,
      value: BigNumberish,
      data: BytesLike,
      predecessor: BytesLike,
      salt: BytesLike
    ],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "hashOperation(address,uint256,bytes,bytes32,bytes32)"
  ): TypedContractMethod<
    [
      target: AddressLike,
      value: BigNumberish,
      data: BytesLike,
      predecessor: BytesLike,
      salt: BytesLike
    ],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "hashOperationBatch"
  ): TypedContractMethod<
    [
      targets: AddressLike[],
      values: BigNumberish[],
      payloads: BytesLike[],
      predecessor: BytesLike,
      salt: BytesLike
    ],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "hashOperationBatch(address[],uint256[],bytes[],bytes32,bytes32)"
  ): TypedContractMethod<
    [
      targets: AddressLike[],
      values: BigNumberish[],
      payloads: BytesLike[],
      predecessor: BytesLike,
      salt: BytesLike
    ],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "isOperation"
  ): TypedContractMethod<[id: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isOperation(bytes32)"
  ): TypedContractMethod<[id: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isOperationDone"
  ): TypedContractMethod<[id: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isOperationDone(bytes32)"
  ): TypedContractMethod<[id: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isOperationPending"
  ): TypedContractMethod<[id: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isOperationPending(bytes32)"
  ): TypedContractMethod<[id: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isOperationReady"
  ): TypedContractMethod<[id: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isOperationReady(bytes32)"
  ): TypedContractMethod<[id: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "onERC1155BatchReceived"
  ): TypedContractMethod<
    [
      arg0: AddressLike,
      arg1: AddressLike,
      arg2: BigNumberish[],
      arg3: BigNumberish[],
      arg4: BytesLike
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "onERC1155BatchReceived(address,address,uint256[],uint256[],bytes)"
  ): TypedContractMethod<
    [
      arg0: AddressLike,
      arg1: AddressLike,
      arg2: BigNumberish[],
      arg3: BigNumberish[],
      arg4: BytesLike
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "onERC1155Received"
  ): TypedContractMethod<
    [
      arg0: AddressLike,
      arg1: AddressLike,
      arg2: BigNumberish,
      arg3: BigNumberish,
      arg4: BytesLike
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "onERC1155Received(address,address,uint256,uint256,bytes)"
  ): TypedContractMethod<
    [
      arg0: AddressLike,
      arg1: AddressLike,
      arg2: BigNumberish,
      arg3: BigNumberish,
      arg4: BytesLike
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "onERC721Received"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike, arg2: BigNumberish, arg3: BytesLike],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "onERC721Received(address,address,uint256,bytes)"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike, arg2: BigNumberish, arg3: BytesLike],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceRole(bytes32,address)"
  ): TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeRole(bytes32,address)"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "rotateKey"
  ): TypedContractMethod<
    [
      bridge: AddressLike,
      keyType: BigNumberish,
      newKey: AddressLike,
      predecessor: BytesLike,
      salt: BytesLike,
      deadline: BigNumberish,
      issuerSignature: BytesLike,
      foundationSignature: BytesLike
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "rotateKey(address,uint8,address,bytes32,bytes32,uint256,bytes,bytes)"
  ): TypedContractMethod<
    [
      bridge: AddressLike,
      keyType: BigNumberish,
      newKey: AddressLike,
      predecessor: BytesLike,
      salt: BytesLike,
      deadline: BigNumberish,
      issuerSignature: BytesLike,
      foundationSignature: BytesLike
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "rotationOperations"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        boolean,
        boolean,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        boolean
      ] & {
        exists: boolean;
        executed: boolean;
        bridge: string;
        newIssuerKey: string;
        newIssuerRecoveryKey: string;
        newFoundationKey: string;
        newAuditorKey: string;
        newGuardianKey: string;
        predecessor: string;
        salt: string;
        usePrimaryKeySetter: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "rotationOperations(bytes32)"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        boolean,
        boolean,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        boolean
      ] & {
        exists: boolean;
        executed: boolean;
        bridge: string;
        newIssuerKey: string;
        newIssuerRecoveryKey: string;
        newFoundationKey: string;
        newAuditorKey: string;
        newGuardianKey: string;
        predecessor: string;
        salt: string;
        usePrimaryKeySetter: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "schedule"
  ): TypedContractMethod<
    [
      target: AddressLike,
      value: BigNumberish,
      data: BytesLike,
      predecessor: BytesLike,
      salt: BytesLike,
      delay: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "schedule(address,uint256,bytes,bytes32,bytes32,uint256)"
  ): TypedContractMethod<
    [
      target: AddressLike,
      value: BigNumberish,
      data: BytesLike,
      predecessor: BytesLike,
      salt: BytesLike,
      delay: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "scheduleBatch"
  ): TypedContractMethod<
    [
      targets: AddressLike[],
      values: BigNumberish[],
      payloads: BytesLike[],
      predecessor: BytesLike,
      salt: BytesLike,
      delay: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "scheduleBatch(address[],uint256[],bytes[],bytes32,bytes32,uint256)"
  ): TypedContractMethod<
    [
      targets: AddressLike[],
      values: BigNumberish[],
      payloads: BytesLike[],
      predecessor: BytesLike,
      salt: BytesLike,
      delay: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "supportsInterface(bytes4)"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "updateDelay"
  ): TypedContractMethod<[newDelay: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateDelay(uint256)"
  ): TypedContractMethod<[newDelay: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "CallExecuted"
  ): TypedContractEvent<
    CallExecutedEvent.InputTuple,
    CallExecutedEvent.OutputTuple,
    CallExecutedEvent.OutputObject
  >;
  getEvent(
    key: "CallExecuted(bytes32,uint256,address,uint256,bytes)"
  ): TypedContractEvent<
    CallExecuted_bytes32_uint256_address_uint256_bytes_Event.InputTuple,
    CallExecuted_bytes32_uint256_address_uint256_bytes_Event.OutputTuple,
    CallExecuted_bytes32_uint256_address_uint256_bytes_Event.OutputObject
  >;
  getEvent(
    key: "CallSalt"
  ): TypedContractEvent<
    CallSaltEvent.InputTuple,
    CallSaltEvent.OutputTuple,
    CallSaltEvent.OutputObject
  >;
  getEvent(
    key: "CallSalt(bytes32,bytes32)"
  ): TypedContractEvent<
    CallSalt_bytes32_bytes32_Event.InputTuple,
    CallSalt_bytes32_bytes32_Event.OutputTuple,
    CallSalt_bytes32_bytes32_Event.OutputObject
  >;
  getEvent(
    key: "CallScheduled"
  ): TypedContractEvent<
    CallScheduledEvent.InputTuple,
    CallScheduledEvent.OutputTuple,
    CallScheduledEvent.OutputObject
  >;
  getEvent(
    key: "CallScheduled(bytes32,uint256,address,uint256,bytes,bytes32,uint256)"
  ): TypedContractEvent<
    CallScheduled_bytes32_uint256_address_uint256_bytes_bytes32_uint256_Event.InputTuple,
    CallScheduled_bytes32_uint256_address_uint256_bytes_bytes32_uint256_Event.OutputTuple,
    CallScheduled_bytes32_uint256_address_uint256_bytes_bytes32_uint256_Event.OutputObject
  >;
  getEvent(
    key: "Cancelled"
  ): TypedContractEvent<
    CancelledEvent.InputTuple,
    CancelledEvent.OutputTuple,
    CancelledEvent.OutputObject
  >;
  getEvent(
    key: "Cancelled(bytes32)"
  ): TypedContractEvent<
    Cancelled_bytes32_Event.InputTuple,
    Cancelled_bytes32_Event.OutputTuple,
    Cancelled_bytes32_Event.OutputObject
  >;
  getEvent(
    key: "KeyRotationExecuted"
  ): TypedContractEvent<
    KeyRotationExecutedEvent.InputTuple,
    KeyRotationExecutedEvent.OutputTuple,
    KeyRotationExecutedEvent.OutputObject
  >;
  getEvent(
    key: "KeyRotationExecuted(bytes32,address,address,address,address,address,address)"
  ): TypedContractEvent<
    KeyRotationExecuted_bytes32_address_address_address_address_address_address_Event.InputTuple,
    KeyRotationExecuted_bytes32_address_address_address_address_address_address_Event.OutputTuple,
    KeyRotationExecuted_bytes32_address_address_address_address_address_address_Event.OutputObject
  >;
  getEvent(
    key: "KeyRotationQueued"
  ): TypedContractEvent<
    KeyRotationQueuedEvent.InputTuple,
    KeyRotationQueuedEvent.OutputTuple,
    KeyRotationQueuedEvent.OutputObject
  >;
  getEvent(
    key: "KeyRotationQueued(bytes32,address,uint8,address,uint256)"
  ): TypedContractEvent<
    KeyRotationQueued_bytes32_address_uint8_address_uint256_Event.InputTuple,
    KeyRotationQueued_bytes32_address_uint8_address_uint256_Event.OutputTuple,
    KeyRotationQueued_bytes32_address_uint8_address_uint256_Event.OutputObject
  >;
  getEvent(
    key: "MinDelayChange"
  ): TypedContractEvent<
    MinDelayChangeEvent.InputTuple,
    MinDelayChangeEvent.OutputTuple,
    MinDelayChangeEvent.OutputObject
  >;
  getEvent(
    key: "MinDelayChange(uint256,uint256)"
  ): TypedContractEvent<
    MinDelayChange_uint256_uint256_Event.InputTuple,
    MinDelayChange_uint256_uint256_Event.OutputTuple,
    MinDelayChange_uint256_uint256_Event.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged(bytes32,bytes32,bytes32)"
  ): TypedContractEvent<
    RoleAdminChanged_bytes32_bytes32_bytes32_Event.InputTuple,
    RoleAdminChanged_bytes32_bytes32_bytes32_Event.OutputTuple,
    RoleAdminChanged_bytes32_bytes32_bytes32_Event.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted(bytes32,address,address)"
  ): TypedContractEvent<
    RoleGranted_bytes32_address_address_Event.InputTuple,
    RoleGranted_bytes32_address_address_Event.OutputTuple,
    RoleGranted_bytes32_address_address_Event.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked(bytes32,address,address)"
  ): TypedContractEvent<
    RoleRevoked_bytes32_address_address_Event.InputTuple,
    RoleRevoked_bytes32_address_address_Event.OutputTuple,
    RoleRevoked_bytes32_address_address_Event.OutputObject
  >;

  filters: {
    "CallExecuted(bytes32,uint256,address,uint256,bytes)": TypedContractEvent<
      CallExecutedEvent.InputTuple,
      CallExecutedEvent.OutputTuple,
      CallExecutedEvent.OutputObject
    >;
    CallExecuted: TypedContractEvent<
      CallExecutedEvent.InputTuple,
      CallExecutedEvent.OutputTuple,
      CallExecutedEvent.OutputObject
    >;

    "CallSalt(bytes32,bytes32)": TypedContractEvent<
      CallSaltEvent.InputTuple,
      CallSaltEvent.OutputTuple,
      CallSaltEvent.OutputObject
    >;
    CallSalt: TypedContractEvent<
      CallSaltEvent.InputTuple,
      CallSaltEvent.OutputTuple,
      CallSaltEvent.OutputObject
    >;

    "CallScheduled(bytes32,uint256,address,uint256,bytes,bytes32,uint256)": TypedContractEvent<
      CallScheduledEvent.InputTuple,
      CallScheduledEvent.OutputTuple,
      CallScheduledEvent.OutputObject
    >;
    CallScheduled: TypedContractEvent<
      CallScheduledEvent.InputTuple,
      CallScheduledEvent.OutputTuple,
      CallScheduledEvent.OutputObject
    >;

    "Cancelled(bytes32)": TypedContractEvent<
      CancelledEvent.InputTuple,
      CancelledEvent.OutputTuple,
      CancelledEvent.OutputObject
    >;
    Cancelled: TypedContractEvent<
      CancelledEvent.InputTuple,
      CancelledEvent.OutputTuple,
      CancelledEvent.OutputObject
    >;

    "KeyRotationExecuted(bytes32,address,address,address,address,address,address)": TypedContractEvent<
      KeyRotationExecutedEvent.InputTuple,
      KeyRotationExecutedEvent.OutputTuple,
      KeyRotationExecutedEvent.OutputObject
    >;
    KeyRotationExecuted: TypedContractEvent<
      KeyRotationExecutedEvent.InputTuple,
      KeyRotationExecutedEvent.OutputTuple,
      KeyRotationExecutedEvent.OutputObject
    >;

    "KeyRotationQueued(bytes32,address,uint8,address,uint256)": TypedContractEvent<
      KeyRotationQueuedEvent.InputTuple,
      KeyRotationQueuedEvent.OutputTuple,
      KeyRotationQueuedEvent.OutputObject
    >;
    KeyRotationQueued: TypedContractEvent<
      KeyRotationQueuedEvent.InputTuple,
      KeyRotationQueuedEvent.OutputTuple,
      KeyRotationQueuedEvent.OutputObject
    >;

    "MinDelayChange(uint256,uint256)": TypedContractEvent<
      MinDelayChangeEvent.InputTuple,
      MinDelayChangeEvent.OutputTuple,
      MinDelayChangeEvent.OutputObject
    >;
    MinDelayChange: TypedContractEvent<
      MinDelayChangeEvent.InputTuple,
      MinDelayChangeEvent.OutputTuple,
      MinDelayChangeEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
  };
}
