/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IInstitutionalBridgeGovernance__factory } from "./IInstitutionalBridgeGovernance__factory";
export { SovereignGovernanceTimelock__factory } from "./SovereignGovernanceTimelock__factory";
