/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface MockMessageTransmitterV2Interface extends Interface {
  getFunction(
    nameOrSignature:
      | "receiveMessage"
      | "receiveMessage(bytes,bytes)"
      | "setShouldSucceed"
      | "setShouldSucceed(bool)"
      | "shouldSucceed"
      | "shouldSucceed()"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "MessageReceived"
      | "MessageReceived(bytes,bytes,bool)"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "receiveMessage",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "receiveMessage(bytes,bytes)",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setShouldSucceed",
    values: [boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setShouldSucceed(bool)",
    values: [boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "shouldSucceed",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "shouldSucceed()",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "receiveMessage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "receiveMessage(bytes,bytes)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setShouldSucceed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setShouldSucceed(bool)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "shouldSucceed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "shouldSucceed()",
    data: BytesLike
  ): Result;
}

export namespace MessageReceivedEvent {
  export type InputTuple = [
    message: BytesLike,
    attestation: BytesLike,
    success: boolean
  ];
  export type OutputTuple = [
    message: string,
    attestation: string,
    success: boolean
  ];
  export interface OutputObject {
    message: string;
    attestation: string;
    success: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface MockMessageTransmitterV2 extends BaseContract {
  connect(runner?: ContractRunner | null): MockMessageTransmitterV2;
  waitForDeployment(): Promise<this>;

  interface: MockMessageTransmitterV2Interface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  receiveMessage: TypedContractMethod<
    [message: BytesLike, attestation: BytesLike],
    [boolean],
    "nonpayable"
  >;

  "receiveMessage(bytes,bytes)": TypedContractMethod<
    [message: BytesLike, attestation: BytesLike],
    [boolean],
    "nonpayable"
  >;

  setShouldSucceed: TypedContractMethod<[value: boolean], [void], "nonpayable">;

  "setShouldSucceed(bool)": TypedContractMethod<
    [value: boolean],
    [void],
    "nonpayable"
  >;

  shouldSucceed: TypedContractMethod<[], [boolean], "view">;

  "shouldSucceed()": TypedContractMethod<[], [boolean], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "receiveMessage"
  ): TypedContractMethod<
    [message: BytesLike, attestation: BytesLike],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "receiveMessage(bytes,bytes)"
  ): TypedContractMethod<
    [message: BytesLike, attestation: BytesLike],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setShouldSucceed"
  ): TypedContractMethod<[value: boolean], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setShouldSucceed(bool)"
  ): TypedContractMethod<[value: boolean], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "shouldSucceed"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "shouldSucceed()"
  ): TypedContractMethod<[], [boolean], "view">;

  getEvent(
    key: "MessageReceived"
  ): TypedContractEvent<
    MessageReceivedEvent.InputTuple,
    MessageReceivedEvent.OutputTuple,
    MessageReceivedEvent.OutputObject
  >;
  getEvent(
    key: "MessageReceived(bytes,bytes,bool)"
  ): TypedContractEvent<
    MessageReceived_bytes_bytes_bool_Event.InputTuple,
    MessageReceived_bytes_bytes_bool_Event.OutputTuple,
    MessageReceived_bytes_bytes_bool_Event.OutputObject
  >;

  filters: {
    "MessageReceived(bytes,bytes,bool)": TypedContractEvent<
      MessageReceivedEvent.InputTuple,
      MessageReceivedEvent.OutputTuple,
      MessageReceivedEvent.OutputObject
    >;
    MessageReceived: TypedContractEvent<
      MessageReceivedEvent.InputTuple,
      MessageReceivedEvent.OutputTuple,
      MessageReceivedEvent.OutputObject
    >;
  };
}
