/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface MockTokenMessengerV2Interface extends Interface {
  getFunction(
    nameOrSignature:
      | "depositForBurn"
      | "depositForBurn(uint256,uint32,bytes32,address)"
      | "nonce"
      | "nonce()"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BurnDeposited"
      | "BurnDeposited(uint64,address,uint256,uint32,bytes32)"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "depositForBurn",
    values: [BigNumberish, BigNumberish, BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "depositForBurn(uint256,uint32,bytes32,address)",
    values: [BigNumberish, BigNumberish, BytesLike, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "nonce", values?: undefined): string;
  encodeFunctionData(functionFragment: "nonce()", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "depositForBurn",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositForBurn(uint256,uint32,bytes32,address)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "nonce", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "nonce()", data: BytesLike): Result;
}

export namespace BurnDepositedEvent {
  export type InputTuple = [
    nonce: BigNumberish,
    token: AddressLike,
    amount: BigNumberish,
    destinationDomain: BigNumberish,
    mintRecipient: BytesLike
  ];
  export type OutputTuple = [
    nonce: bigint,
    token: string,
    amount: bigint,
    destinationDomain: bigint,
    mintRecipient: string
  ];
  export interface OutputObject {
    nonce: bigint;
    token: string;
    amount: bigint;
    destinationDomain: bigint;
    mintRecipient: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface MockTokenMessengerV2 extends BaseContract {
  connect(runner?: ContractRunner | null): MockTokenMessengerV2;
  waitForDeployment(): Promise<this>;

  interface: MockTokenMessengerV2Interface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  depositForBurn: TypedContractMethod<
    [
      amount: BigNumberish,
      destinationDomain: BigNumberish,
      mintRecipient: BytesLike,
      burnToken: AddressLike
    ],
    [bigint],
    "nonpayable"
  >;

  "depositForBurn(uint256,uint32,bytes32,address)": TypedContractMethod<
    [
      amount: BigNumberish,
      destinationDomain: BigNumberish,
      mintRecipient: BytesLike,
      burnToken: AddressLike
    ],
    [bigint],
    "nonpayable"
  >;

  nonce: TypedContractMethod<[], [bigint], "view">;

  "nonce()": TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "depositForBurn"
  ): TypedContractMethod<
    [
      amount: BigNumberish,
      destinationDomain: BigNumberish,
      mintRecipient: BytesLike,
      burnToken: AddressLike
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "depositForBurn(uint256,uint32,bytes32,address)"
  ): TypedContractMethod<
    [
      amount: BigNumberish,
      destinationDomain: BigNumberish,
      mintRecipient: BytesLike,
      burnToken: AddressLike
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "nonce"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "nonce()"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "BurnDeposited"
  ): TypedContractEvent<
    BurnDepositedEvent.InputTuple,
    BurnDepositedEvent.OutputTuple,
    BurnDepositedEvent.OutputObject
  >;
  getEvent(
    key: "BurnDeposited(uint64,address,uint256,uint32,bytes32)"
  ): TypedContractEvent<
    BurnDeposited_uint64_address_uint256_uint32_bytes32_Event.InputTuple,
    BurnDeposited_uint64_address_uint256_uint32_bytes32_Event.OutputTuple,
    BurnDeposited_uint64_address_uint256_uint32_bytes32_Event.OutputObject
  >;

  filters: {
    "BurnDeposited(uint64,address,uint256,uint32,bytes32)": TypedContractEvent<
      BurnDepositedEvent.InputTuple,
      BurnDepositedEvent.OutputTuple,
      BurnDepositedEvent.OutputObject
    >;
    BurnDeposited: TypedContractEvent<
      BurnDepositedEvent.InputTuple,
      BurnDepositedEvent.OutputTuple,
      BurnDepositedEvent.OutputObject
    >;
  };
}
