/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface MockInstitutionalBridgeMonitorInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "lastMonitoredAssetId"
      | "lastMonitoredAssetId()"
      | "monitorCallCount"
      | "monitorCallCount()"
      | "monitorCallsByAsset"
      | "monitorCallsByAsset(bytes32)"
      | "monitorReserve"
      | "monitorReserve(bytes32)"
      | "setShouldRevert"
      | "setShouldRevert(bytes32,bool)"
      | "shouldRevertForAsset"
      | "shouldRevertForAsset(bytes32)"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "ReserveMonitored" | "ReserveMonitored(bytes32)"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "lastMonitoredAssetId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "lastMonitoredAssetId()",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "monitorCallCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "monitorCallCount()",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "monitorCallsByAsset",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "monitorCallsByAsset(bytes32)",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "monitorReserve",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "monitorReserve(bytes32)",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setShouldRevert",
    values: [BytesLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setShouldRevert(bytes32,bool)",
    values: [BytesLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "shouldRevertForAsset",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "shouldRevertForAsset(bytes32)",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "lastMonitoredAssetId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lastMonitoredAssetId()",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "monitorCallCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "monitorCallCount()",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "monitorCallsByAsset",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "monitorCallsByAsset(bytes32)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "monitorReserve",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "monitorReserve(bytes32)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setShouldRevert",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setShouldRevert(bytes32,bool)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "shouldRevertForAsset",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "shouldRevertForAsset(bytes32)",
    data: BytesLike
  ): Result;
}

export namespace ReserveMonitoredEvent {
  export type InputTuple = [assetId: BytesLike];
  export type OutputTuple = [assetId: string];
  export interface OutputObject {
    assetId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface MockInstitutionalBridgeMonitor extends BaseContract {
  connect(runner?: ContractRunner | null): MockInstitutionalBridgeMonitor;
  waitForDeployment(): Promise<this>;

  interface: MockInstitutionalBridgeMonitorInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  lastMonitoredAssetId: TypedContractMethod<[], [string], "view">;

  "lastMonitoredAssetId()": TypedContractMethod<[], [string], "view">;

  monitorCallCount: TypedContractMethod<[], [bigint], "view">;

  "monitorCallCount()": TypedContractMethod<[], [bigint], "view">;

  monitorCallsByAsset: TypedContractMethod<[arg0: BytesLike], [bigint], "view">;

  "monitorCallsByAsset(bytes32)": TypedContractMethod<
    [arg0: BytesLike],
    [bigint],
    "view"
  >;

  monitorReserve: TypedContractMethod<
    [assetId: BytesLike],
    [void],
    "nonpayable"
  >;

  "monitorReserve(bytes32)": TypedContractMethod<
    [assetId: BytesLike],
    [void],
    "nonpayable"
  >;

  setShouldRevert: TypedContractMethod<
    [assetId: BytesLike, shouldRevert: boolean],
    [void],
    "nonpayable"
  >;

  "setShouldRevert(bytes32,bool)": TypedContractMethod<
    [assetId: BytesLike, shouldRevert: boolean],
    [void],
    "nonpayable"
  >;

  shouldRevertForAsset: TypedContractMethod<
    [arg0: BytesLike],
    [boolean],
    "view"
  >;

  "shouldRevertForAsset(bytes32)": TypedContractMethod<
    [arg0: BytesLike],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "lastMonitoredAssetId"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "lastMonitoredAssetId()"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "monitorCallCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "monitorCallCount()"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "monitorCallsByAsset"
  ): TypedContractMethod<[arg0: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "monitorCallsByAsset(bytes32)"
  ): TypedContractMethod<[arg0: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "monitorReserve"
  ): TypedContractMethod<[assetId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "monitorReserve(bytes32)"
  ): TypedContractMethod<[assetId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setShouldRevert"
  ): TypedContractMethod<
    [assetId: BytesLike, shouldRevert: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setShouldRevert(bytes32,bool)"
  ): TypedContractMethod<
    [assetId: BytesLike, shouldRevert: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "shouldRevertForAsset"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "shouldRevertForAsset(bytes32)"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  getEvent(
    key: "ReserveMonitored"
  ): TypedContractEvent<
    ReserveMonitoredEvent.InputTuple,
    ReserveMonitoredEvent.OutputTuple,
    ReserveMonitoredEvent.OutputObject
  >;
  getEvent(
    key: "ReserveMonitored(bytes32)"
  ): TypedContractEvent<
    ReserveMonitored_bytes32_Event.InputTuple,
    ReserveMonitored_bytes32_Event.OutputTuple,
    ReserveMonitored_bytes32_Event.OutputObject
  >;

  filters: {
    "ReserveMonitored(bytes32)": TypedContractEvent<
      ReserveMonitoredEvent.InputTuple,
      ReserveMonitoredEvent.OutputTuple,
      ReserveMonitoredEvent.OutputObject
    >;
    ReserveMonitored: TypedContractEvent<
      ReserveMonitoredEvent.InputTuple,
      ReserveMonitoredEvent.OutputTuple,
      ReserveMonitoredEvent.OutputObject
    >;
  };
}
