/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface InstitutionalReserveAutomationKeeperInterface
  extends Interface {
  getFunction(
    nameOrSignature:
      | "acceptOwnership"
      | "acceptOwnership()"
      | "bridge"
      | "bridge()"
      | "checkUpkeep"
      | "checkUpkeep(bytes)"
      | "getTrackedAssets"
      | "getTrackedAssets()"
      | "isAssetEnabled"
      | "isAssetEnabled(bytes32)"
      | "isTrackedAsset"
      | "isTrackedAsset(bytes32)"
      | "maxAssetsPerRun"
      | "maxAssetsPerRun()"
      | "owner"
      | "owner()"
      | "pendingOwner"
      | "pendingOwner()"
      | "performUpkeep"
      | "performUpkeep(bytes)"
      | "setAsset"
      | "setAsset(bytes32,bool)"
      | "setAssets"
      | "setAssets(bytes32[],bool)"
      | "setBridge"
      | "setBridge(address)"
      | "setMaxAssetsPerRun"
      | "setMaxAssetsPerRun(uint256)"
      | "transferOwnership"
      | "transferOwnership(address)"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AssetConfigured"
      | "AssetConfigured(bytes32,bool)"
      | "BridgeUpdated"
      | "BridgeUpdated(address,address)"
      | "MaxAssetsPerRunUpdated"
      | "MaxAssetsPerRunUpdated(uint256,uint256)"
      | "OwnershipTransferStarted"
      | "OwnershipTransferStarted(address,address)"
      | "OwnershipTransferred"
      | "OwnershipTransferred(address,address)"
      | "ReserveMonitorFailed"
      | "ReserveMonitorFailed(bytes32,bytes)"
      | "ReserveMonitorTriggered"
      | "ReserveMonitorTriggered(bytes32)"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "acceptOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "acceptOwnership()",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "bridge", values?: undefined): string;
  encodeFunctionData(functionFragment: "bridge()", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "checkUpkeep",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "checkUpkeep(bytes)",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTrackedAssets",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTrackedAssets()",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isAssetEnabled",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isAssetEnabled(bytes32)",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isTrackedAsset",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isTrackedAsset(bytes32)",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "maxAssetsPerRun",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "maxAssetsPerRun()",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner()", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pendingOwner",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "pendingOwner()",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "performUpkeep",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "performUpkeep(bytes)",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setAsset",
    values: [BytesLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setAsset(bytes32,bool)",
    values: [BytesLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setAssets",
    values: [BytesLike[], boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setAssets(bytes32[],bool)",
    values: [BytesLike[], boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setBridge",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setBridge(address)",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setMaxAssetsPerRun",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setMaxAssetsPerRun(uint256)",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership(address)",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "acceptOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "acceptOwnership()",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "bridge", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "bridge()", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "checkUpkeep",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkUpkeep(bytes)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTrackedAssets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTrackedAssets()",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isAssetEnabled",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isAssetEnabled(bytes32)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isTrackedAsset",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isTrackedAsset(bytes32)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "maxAssetsPerRun",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "maxAssetsPerRun()",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner()", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pendingOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "pendingOwner()",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "performUpkeep",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "performUpkeep(bytes)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setAsset", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setAsset(bytes32,bool)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setAssets", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setAssets(bytes32[],bool)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setBridge", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setBridge(address)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMaxAssetsPerRun",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMaxAssetsPerRun(uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership(address)",
    data: BytesLike
  ): Result;
}

export namespace AssetConfiguredEvent {
  export type InputTuple = [assetId: BytesLike, enabled: boolean];
  export type OutputTuple = [assetId: string, enabled: boolean];
  export interface OutputObject {
    assetId: string;
    enabled: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BridgeUpdatedEvent {
  export type InputTuple = [
    previousBridge: AddressLike,
    newBridge: AddressLike
  ];
  export type OutputTuple = [previousBridge: string, newBridge: string];
  export interface OutputObject {
    previousBridge: string;
    newBridge: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MaxAssetsPerRunUpdatedEvent {
  export type InputTuple = [oldValue: BigNumberish, newValue: BigNumberish];
  export type OutputTuple = [oldValue: bigint, newValue: bigint];
  export interface OutputObject {
    oldValue: bigint;
    newValue: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferStartedEvent {
  export type InputTuple = [
    previousOwner: AddressLike,
    pendingOwner: AddressLike
  ];
  export type OutputTuple = [previousOwner: string, pendingOwner: string];
  export interface OutputObject {
    previousOwner: string;
    pendingOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReserveMonitorFailedEvent {
  export type InputTuple = [assetId: BytesLike, reason: BytesLike];
  export type OutputTuple = [assetId: string, reason: string];
  export interface OutputObject {
    assetId: string;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReserveMonitorTriggeredEvent {
  export type InputTuple = [assetId: BytesLike];
  export type OutputTuple = [assetId: string];
  export interface OutputObject {
    assetId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface InstitutionalReserveAutomationKeeper extends BaseContract {
  connect(runner?: ContractRunner | null): InstitutionalReserveAutomationKeeper;
  waitForDeployment(): Promise<this>;

  interface: InstitutionalReserveAutomationKeeperInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  acceptOwnership: TypedContractMethod<[], [void], "nonpayable">;

  "acceptOwnership()": TypedContractMethod<[], [void], "nonpayable">;

  bridge: TypedContractMethod<[], [string], "view">;

  "bridge()": TypedContractMethod<[], [string], "view">;

  checkUpkeep: TypedContractMethod<
    [arg0: BytesLike],
    [[boolean, string] & { upkeepNeeded: boolean; performData: string }],
    "view"
  >;

  "checkUpkeep(bytes)": TypedContractMethod<
    [arg0: BytesLike],
    [[boolean, string] & { upkeepNeeded: boolean; performData: string }],
    "view"
  >;

  getTrackedAssets: TypedContractMethod<[], [string[]], "view">;

  "getTrackedAssets()": TypedContractMethod<[], [string[]], "view">;

  isAssetEnabled: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  "isAssetEnabled(bytes32)": TypedContractMethod<
    [arg0: BytesLike],
    [boolean],
    "view"
  >;

  isTrackedAsset: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  "isTrackedAsset(bytes32)": TypedContractMethod<
    [arg0: BytesLike],
    [boolean],
    "view"
  >;

  maxAssetsPerRun: TypedContractMethod<[], [bigint], "view">;

  "maxAssetsPerRun()": TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  "owner()": TypedContractMethod<[], [string], "view">;

  pendingOwner: TypedContractMethod<[], [string], "view">;

  "pendingOwner()": TypedContractMethod<[], [string], "view">;

  performUpkeep: TypedContractMethod<
    [performData: BytesLike],
    [void],
    "nonpayable"
  >;

  "performUpkeep(bytes)": TypedContractMethod<
    [performData: BytesLike],
    [void],
    "nonpayable"
  >;

  setAsset: TypedContractMethod<
    [assetId: BytesLike, enabled: boolean],
    [void],
    "nonpayable"
  >;

  "setAsset(bytes32,bool)": TypedContractMethod<
    [assetId: BytesLike, enabled: boolean],
    [void],
    "nonpayable"
  >;

  setAssets: TypedContractMethod<
    [assetIds: BytesLike[], enabled: boolean],
    [void],
    "nonpayable"
  >;

  "setAssets(bytes32[],bool)": TypedContractMethod<
    [assetIds: BytesLike[], enabled: boolean],
    [void],
    "nonpayable"
  >;

  setBridge: TypedContractMethod<
    [bridgeAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  "setBridge(address)": TypedContractMethod<
    [bridgeAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  setMaxAssetsPerRun: TypedContractMethod<
    [newMax: BigNumberish],
    [void],
    "nonpayable"
  >;

  "setMaxAssetsPerRun(uint256)": TypedContractMethod<
    [newMax: BigNumberish],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  "transferOwnership(address)": TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "acceptOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "acceptOwnership()"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "bridge"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "bridge()"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "checkUpkeep"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [[boolean, string] & { upkeepNeeded: boolean; performData: string }],
    "view"
  >;
  getFunction(
    nameOrSignature: "checkUpkeep(bytes)"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [[boolean, string] & { upkeepNeeded: boolean; performData: string }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTrackedAssets"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getTrackedAssets()"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "isAssetEnabled"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isAssetEnabled(bytes32)"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isTrackedAsset"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isTrackedAsset(bytes32)"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "maxAssetsPerRun"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "maxAssetsPerRun()"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner()"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pendingOwner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pendingOwner()"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "performUpkeep"
  ): TypedContractMethod<[performData: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "performUpkeep(bytes)"
  ): TypedContractMethod<[performData: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setAsset"
  ): TypedContractMethod<
    [assetId: BytesLike, enabled: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setAsset(bytes32,bool)"
  ): TypedContractMethod<
    [assetId: BytesLike, enabled: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setAssets"
  ): TypedContractMethod<
    [assetIds: BytesLike[], enabled: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setAssets(bytes32[],bool)"
  ): TypedContractMethod<
    [assetIds: BytesLike[], enabled: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setBridge"
  ): TypedContractMethod<[bridgeAddress: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setBridge(address)"
  ): TypedContractMethod<[bridgeAddress: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setMaxAssetsPerRun"
  ): TypedContractMethod<[newMax: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setMaxAssetsPerRun(uint256)"
  ): TypedContractMethod<[newMax: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership(address)"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "AssetConfigured"
  ): TypedContractEvent<
    AssetConfiguredEvent.InputTuple,
    AssetConfiguredEvent.OutputTuple,
    AssetConfiguredEvent.OutputObject
  >;
  getEvent(
    key: "AssetConfigured(bytes32,bool)"
  ): TypedContractEvent<
    AssetConfigured_bytes32_bool_Event.InputTuple,
    AssetConfigured_bytes32_bool_Event.OutputTuple,
    AssetConfigured_bytes32_bool_Event.OutputObject
  >;
  getEvent(
    key: "BridgeUpdated"
  ): TypedContractEvent<
    BridgeUpdatedEvent.InputTuple,
    BridgeUpdatedEvent.OutputTuple,
    BridgeUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "BridgeUpdated(address,address)"
  ): TypedContractEvent<
    BridgeUpdated_address_address_Event.InputTuple,
    BridgeUpdated_address_address_Event.OutputTuple,
    BridgeUpdated_address_address_Event.OutputObject
  >;
  getEvent(
    key: "MaxAssetsPerRunUpdated"
  ): TypedContractEvent<
    MaxAssetsPerRunUpdatedEvent.InputTuple,
    MaxAssetsPerRunUpdatedEvent.OutputTuple,
    MaxAssetsPerRunUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "MaxAssetsPerRunUpdated(uint256,uint256)"
  ): TypedContractEvent<
    MaxAssetsPerRunUpdated_uint256_uint256_Event.InputTuple,
    MaxAssetsPerRunUpdated_uint256_uint256_Event.OutputTuple,
    MaxAssetsPerRunUpdated_uint256_uint256_Event.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferStarted"
  ): TypedContractEvent<
    OwnershipTransferStartedEvent.InputTuple,
    OwnershipTransferStartedEvent.OutputTuple,
    OwnershipTransferStartedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferStarted(address,address)"
  ): TypedContractEvent<
    OwnershipTransferStarted_address_address_Event.InputTuple,
    OwnershipTransferStarted_address_address_Event.OutputTuple,
    OwnershipTransferStarted_address_address_Event.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred(address,address)"
  ): TypedContractEvent<
    OwnershipTransferred_address_address_Event.InputTuple,
    OwnershipTransferred_address_address_Event.OutputTuple,
    OwnershipTransferred_address_address_Event.OutputObject
  >;
  getEvent(
    key: "ReserveMonitorFailed"
  ): TypedContractEvent<
    ReserveMonitorFailedEvent.InputTuple,
    ReserveMonitorFailedEvent.OutputTuple,
    ReserveMonitorFailedEvent.OutputObject
  >;
  getEvent(
    key: "ReserveMonitorFailed(bytes32,bytes)"
  ): TypedContractEvent<
    ReserveMonitorFailed_bytes32_bytes_Event.InputTuple,
    ReserveMonitorFailed_bytes32_bytes_Event.OutputTuple,
    ReserveMonitorFailed_bytes32_bytes_Event.OutputObject
  >;
  getEvent(
    key: "ReserveMonitorTriggered"
  ): TypedContractEvent<
    ReserveMonitorTriggeredEvent.InputTuple,
    ReserveMonitorTriggeredEvent.OutputTuple,
    ReserveMonitorTriggeredEvent.OutputObject
  >;
  getEvent(
    key: "ReserveMonitorTriggered(bytes32)"
  ): TypedContractEvent<
    ReserveMonitorTriggered_bytes32_Event.InputTuple,
    ReserveMonitorTriggered_bytes32_Event.OutputTuple,
    ReserveMonitorTriggered_bytes32_Event.OutputObject
  >;

  filters: {
    "AssetConfigured(bytes32,bool)": TypedContractEvent<
      AssetConfiguredEvent.InputTuple,
      AssetConfiguredEvent.OutputTuple,
      AssetConfiguredEvent.OutputObject
    >;
    AssetConfigured: TypedContractEvent<
      AssetConfiguredEvent.InputTuple,
      AssetConfiguredEvent.OutputTuple,
      AssetConfiguredEvent.OutputObject
    >;

    "BridgeUpdated(address,address)": TypedContractEvent<
      BridgeUpdatedEvent.InputTuple,
      BridgeUpdatedEvent.OutputTuple,
      BridgeUpdatedEvent.OutputObject
    >;
    BridgeUpdated: TypedContractEvent<
      BridgeUpdatedEvent.InputTuple,
      BridgeUpdatedEvent.OutputTuple,
      BridgeUpdatedEvent.OutputObject
    >;

    "MaxAssetsPerRunUpdated(uint256,uint256)": TypedContractEvent<
      MaxAssetsPerRunUpdatedEvent.InputTuple,
      MaxAssetsPerRunUpdatedEvent.OutputTuple,
      MaxAssetsPerRunUpdatedEvent.OutputObject
    >;
    MaxAssetsPerRunUpdated: TypedContractEvent<
      MaxAssetsPerRunUpdatedEvent.InputTuple,
      MaxAssetsPerRunUpdatedEvent.OutputTuple,
      MaxAssetsPerRunUpdatedEvent.OutputObject
    >;

    "OwnershipTransferStarted(address,address)": TypedContractEvent<
      OwnershipTransferStartedEvent.InputTuple,
      OwnershipTransferStartedEvent.OutputTuple,
      OwnershipTransferStartedEvent.OutputObject
    >;
    OwnershipTransferStarted: TypedContractEvent<
      OwnershipTransferStartedEvent.InputTuple,
      OwnershipTransferStartedEvent.OutputTuple,
      OwnershipTransferStartedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "ReserveMonitorFailed(bytes32,bytes)": TypedContractEvent<
      ReserveMonitorFailedEvent.InputTuple,
      ReserveMonitorFailedEvent.OutputTuple,
      ReserveMonitorFailedEvent.OutputObject
    >;
    ReserveMonitorFailed: TypedContractEvent<
      ReserveMonitorFailedEvent.InputTuple,
      ReserveMonitorFailedEvent.OutputTuple,
      ReserveMonitorFailedEvent.OutputObject
    >;

    "ReserveMonitorTriggered(bytes32)": TypedContractEvent<
      ReserveMonitorTriggeredEvent.InputTuple,
      ReserveMonitorTriggeredEvent.OutputTuple,
      ReserveMonitorTriggeredEvent.OutputObject
    >;
    ReserveMonitorTriggered: TypedContractEvent<
      ReserveMonitorTriggeredEvent.InputTuple,
      ReserveMonitorTriggeredEvent.OutputTuple,
      ReserveMonitorTriggeredEvent.OutputObject
    >;
  };
}
